"""should probably jinja-fy this"""
PREFIX ='''\
##
## This code was generated by a tool.
## All manual changes will be overwritten!
##
## pyrd 0.1.0
##
from pyrd import *

def standardize_result(result):
    """ Return a ParseObjectBoth inside of a ParseObjectEither
    """
    if not isinstance(result,ParseObjectEither):
        result = ParseObjectEither(result, 0)
    if not isinstance(result.choice,ParseObjectBoth):
        both = ParseObjectBoth()
        both.append(result.choice)
        result.choice = both
    return result

'''
CLASS_TEMPLATE = """\
class {ID}(Parser):
{HANDLER}
{PARSER}
"""

PARSE_TEMPLATE = """\
    def parse(self, string):
        parsed = ({PARSERS}).parse(string)
        if parsed:
            parsed.result = standardize_result(parsed.result)
            parsed.result = self.handle_parsed(parsed.result)
        return parsed
"""

HANDLER_TEMPLATE = """\
    def handle_parsed(self,parsed_choice):
        parsed = parsed_choice.choice
{CODE}
"""
CHOICE_TEMPLATE = """\
        if parsed_choice.index == {IDX}:
            {IDS}
            {FUNCTION}
"""
